MySchedulingVKR/Models/ScheduleTeacher.cs
using System;
using System.Collections.Generic;

namespace MySchedulingVKR.Models;

public partial class ScheduleTeacher
{
    public int ScheduleId { get; set; }

    public int TeacherId { get; set; }

    public virtual Schedule? Schedule { get; set; } = null!;

    public virtual Teacher? Teacher { get; set; } = null!;
}

MySchedulingVKR/Models/Teacher.cs
using System;
using System.Collections.Generic;

namespace MySchedulingVKR.Models;

public partial class Teacher
{
    public int Id { get; set; }

    public string Login { get; set; } = null!;

    public string Password { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string Surname { get; set; } = null!;

    public int? SubjectId { get; set; }

    public int? OrganizationId { get; set; }

    public virtual Organization? Organization { get; set; }

    public virtual Subject? Subject { get; set; }

    public virtual ICollection<TeacherAccess> TeacherAccesses { get; set; } = new List<TeacherAccess>();

    public virtual ICollection<ScheduleTeacher> ScheduleTeachers { get; set; } = new List<ScheduleTeacher>();
}

MySchedulingVKR/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulingVKR;
using MySchedulingVKR.Models;
using static MySchedulingVKR.Models.Lesson;

namespace MySchedulingVKR.Controllers
{
    public class LessonsController : Controller
    {
        private readonly DbSchedulingContext _context;

        public LessonsController(DbSchedulingContext context)
        {
            _context = context;
        }

        //Список занятий
        // GET: Lessons
        public async Task<IActionResult> Index()
        {
            return View(await _context.Lessons.ToListAsync());
        }

        //Информация о занятии
        // GET: Lessons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lessons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }
        
        //Создание занятия
        // GET: Lessons/Create
        public IActionResult Create()
        {
            ViewBag.DayOfWeeks = Enum.GetValues(typeof(DayOfWeekEnum))
                           .Cast<DayOfWeekEnum>()
                           .Select(d => new SelectListItem
                           {
                               Value = d.ToString(),
                               Text = d.ToString()
                           })
                           .ToList();
            return View();
        }
        // POST: Lessons/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DayOfTheWeek,Time,Date")] Lesson lesson)
        {
            int TeacherId = Convert.ToInt32(TempData["TeacherId"]);

            if (ModelState.IsValid)
            {
                var teacherAccess = new TeacherAccess();
                teacherAccess.TeacherId = TeacherId;
                teacherAccess.LessonId = lesson.Id;
                teacherAccess.Access = true;

                lesson.TeacherAccesses.Add(teacherAccess);
                
                _context.Add(lesson);
                _context.Add(teacherAccess);

                await _context.SaveChangesAsync();

                return RedirectToAction("Menu", "Teachers", new { id = TeacherId });
            }

            return View(lesson);
        }

        //Редактирование занятия
        // GET: Lessons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lessons.FindAsync(id);
            if (lesson == null)
            {
                return NotFound();
            }
            return View(lesson);
        }
        // POST: Lessons/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DayOfTheWeek,Time,Date")] Lesson lesson)
        {
            int TeacherId = Convert.ToInt32(TempData["TeacherId"]);
            if (id != lesson.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lesson);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LessonExists(lesson.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Menu", "Teachers", new { id = TeacherId });
            }
            return View(lesson);
        }

        //Удаление занятия
        // GET: Lessons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lessons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }
        // POST: Lessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            int TeacherId = Convert.ToInt32(TempData["TeacherId"]);
            var lesson = await _context.Lessons.FindAsync(id);
            if (lesson != null)
            {
                _context.Lessons.Remove(lesson);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Menu", "Teachers", new { id = TeacherId });
        }

        private bool LessonExists(int id)
        {
            return _context.Lessons.Any(e => e.Id == id);
        }
    }
}

MySchedulingVKR/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulingVKR;
using MySchedulingVKR.Models;
using MySchedulingVKR.ViewModels;

namespace MySchedulingVKR.Controllers
{
    public class TeachersController : Controller
    {
        private readonly DbSchedulingContext _context;

        public TeachersController(DbSchedulingContext context)
        {
            _context = context;
        }

        //Авторизация преподавателя
        // GET: Organizations/Authorization
        public IActionResult Authorization()
        {
            return View();
        }
        // POST: Organizations/Authorization
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Authorization([Bind("Login,Password")] Teacher teacher)
        {

            var user = await _context.Teachers.FirstOrDefaultAsync(o => o.Login == teacher.Login && o.Password == teacher.Password);

            // Проверка введенных данных пользователя
            if (user != null)
            {
                return RedirectToAction("Menu", "Teachers", new { id = user.Id });
            }
            else
            {
                ViewBag.ErrorMessage = "Неверный логин или пароль";
                return View(user);
            }
        }

        //Меню преподавателя
        //GET: Teachers/MainPage
        public async Task<IActionResult> Menu(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = new TeacherViewLesson();
            viewModel.Teachers = await _context.Teachers
                .Include(t => t.TeacherAccesses)
                    .ThenInclude(t => t.Lesson)
                .Include(o => o.Organization)
                .Include(t => t.Subject)
                .AsNoTracking()
                .ToListAsync();

            if (id != null)
            {
                ViewData["Id"] = id;

                TempData["TeacherId"] = id;

                Teacher teacher = viewModel.Teachers.Where(
                    o => o.Id == id).Single();

                viewModel.Teacher = teacher;

                viewModel.Lessons = teacher.TeacherAccesses.Select(o => o.Lesson);

                viewModel.TeachersAccesses = teacher.TeacherAccesses;
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ScheduleTeachers(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Teachers
                .Include(t => t.Subject)
                .Include(t => t.ScheduleTeachers)
                    .ThenInclude(t => t.Schedule)
                    .ThenInclude(s => s.Lesson)
                .Include(t => t.ScheduleTeachers)
                    .ThenInclude(t => t.Schedule)
                .FirstOrDefaultAsync(t => t.Id == id);
                
            return View(schedule);
        }

        //Список преподавателей
        // GET: Teachers
        public async Task<IActionResult> Index()
        {
            var dbSchedulingContext = _context.Teachers.Include(t => t.Organization).Include(t => t.Subject);
            return View(await dbSchedulingContext.ToListAsync());
        }

        //Информация о преподавателе
        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .Include(t => t.Organization)
                .Include(t => t.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        //Создание преподавателя
        // GET: Teachers/Create
        [HttpGet]
        public IActionResult Create()
        {
            int organizationId = Convert.ToInt32(TempData["OrganizationId"]);
            Teacher teacher = new Teacher();
            teacher.OrganizationId = organizationId;

            var organization = _context.Organizations
                                          .Include(o => o.OrganizationSubjects)
                                              .ThenInclude(o => o.Subject)
                                          .FirstOrDefault(o => o.Id == organizationId);
            if (organization != null)
            {
                ViewData["SubjectName"] = new SelectList(organization.OrganizationSubjects.Select(o => o.Subject), "Id", "Name");
            }

            return View(teacher);
        }
        // POST: Teachers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Login,Password,Name,Surname,SubjectId, OrganizationId")] Teacher teacher)
        {
            int organizationId = (int)teacher.OrganizationId;

            var existingTeacher = await _context.Teachers.FirstOrDefaultAsync(o => o.Login == teacher.Login);

            if (existingTeacher != null)
            {
                ModelState.AddModelError("Login", "Логин уже используется.");
                return View(teacher);
            }
            else if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction("Menu", "Organizations", new { id = organizationId });
            }

            var organization = _context.Organizations
                                          .Include(o => o.OrganizationSubjects)
                                              .ThenInclude(o => o.Subject)
                                          .FirstOrDefault(o => o.Id == organizationId);
            if (organization != null)
            {
                ViewData["SubjectName"] = new SelectList(organization.OrganizationSubjects.Select(o => o.Subject), "Id", "Name");
            }

            return View(teacher);
        }

        //Редактирование преподавателя
        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            int organizationId = Convert.ToInt32(TempData["OrganizationId"]);
            var organization = _context.Organizations
                                          .Include(o => o.OrganizationSubjects)
                                              .ThenInclude(o => o.Subject)
                                          .FirstOrDefault(o => o.Id == organizationId);
            if (organization != null)
            {
                ViewData["SubjectName"] = new SelectList(organization.OrganizationSubjects.Select(o => o.Subject), "Id", "Name");
            }

            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);

            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }
        // POST: Teachers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Login,Password,Name,Surname,SubjectId, OrganizationId")] Teacher teacher)
        {
            var existingTeacher = await _context.Teachers.FirstOrDefaultAsync(o => o.Login == teacher.Login && o.Id != id);
            if (existingTeacher != null)
            {
                ModelState.AddModelError("Login", "Логин уже используется.");
                return View(teacher);
            }

            else if (id != teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Menu", "Organizations", new { id = teacher.OrganizationId });
            }
            var organization = _context.Organizations
                                          .Include(o => o.OrganizationSubjects)
                                              .ThenInclude(o => o.Subject)
                                          .FirstOrDefault(o => o.Id == teacher.OrganizationId);
            if (organization != null)
            {
                ViewData["SubjectName"] = new SelectList(organization.OrganizationSubjects.Select(o => o.Subject), "Id", "Name");
            }
            return View(teacher);
        }

        // GET: Teachers/EditTeacher/5
        public async Task<IActionResult> EditTeacher(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);

            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/EditTeacher/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditTeacher(int id, [Bind("Id,Login,Password,Name,Surname,SubjectId, OrganizationId")] Teacher teacher)
        {
            var existingTeacher = await _context.Teachers.FirstOrDefaultAsync(o => o.Login == teacher.Login && o.Id != id);
            if (existingTeacher != null)
            {

MySchedulingVKR/Views/Teachers/Authorization.cshtml
@model MySchedulingVKR.Models.Teacher
@{
    ViewData["Title"] = "Authorization";
}

<style>
    h2 {
        margin-top: 50px;
        font-size: 32px;
        color: #122400;
        text-align: center; /* Центрируем заголовки */
        padding-bottom: 50px;
    }

    form {
        text-align: center;
        width: 300px;
        margin: 0 auto;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }

    label {
        display: block;
        margin-top: 20px;
    }

    input[type="text"], input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    input[type="checkbox"] {
        margin-top: 25px;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        margin-top: 20px;
        background-color: #77804f;
        color: white;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        button:hover {
            background-color: #0056b3;
        }

    p {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

        a:hover {
            text-decoration: underline;
        }
</style>

<h2>Авторизация преподавателя</h2>

<form asp-action="Authorization" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <p class="text-danger">@ViewBag.ErrorMessage</p>

    <label for="login">Логин:</label>
    <input asp-for="Login" type="text" id="login" name="login" required><br>

    <label for="password">Пароль:</label>
    <input asp-for="Password" type="password" id="password" name="password" required><br>

    <button type="submit">Войти</button>
</form>

MySchedulingVKR/Views/Teachers/Create.cshtml
@model MySchedulingVKR.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<div style="margin-left: 50px;">
    <h1>Добавление преподавателя</h1>

    <h4>Преподаватель</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Login" class="control-label">Логин</label>
                    <input asp-for="Login" class="form-control" />
                    <span asp-validation-for="Login" class="text-danger"></span><br />
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label">Пароль</label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span><br />
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Имя</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span><br />
                </div>
                <div class="form-group">
                    <label asp-for="Surname" class="control-label">Фамилия</label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span><br />
                </div>
                <div class="form-group">
                    <label asp-for="SubjectId" class="control-label">Предмет</label>
                    <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectName"></select>

                    <input type="hidden" name="OrganizationId" value="@Model.OrganizationId" />
                </div>
                <div class="form-group">
                    <br /><input style="font-size: 16px;" type="submit" value="Добавить" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MySchedulingVKR/Views/Teachers/Delete.cshtml
@model MySchedulingVKR.Models.Teacher

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Login)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Organization)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Organization.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MySchedulingVKR/Views/Teachers/Details.cshtml
@model MySchedulingVKR.Models.Teacher

@{
    ViewData["Title"] = "Details";
}
<div style="margin-left: 50px;">
    <h1>Информация о преподавателе</h1>

    <div>
        <h4>Преподаватель</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Логин
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Login)
            </dd>
            <dt class="col-sm-2">
                Пароль
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Password)
            </dd>
            <dt class="col-sm-2">
                Имя
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                Фамилия
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Surname)
            </dd>
            <dt class="col-sm-2">
                Название организации
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Organization.Name)
            </dd>
            <dt class="col-sm-2">
                Предмет
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Subject.Name)
            </dd>
        </dl>
    </div>
</div>

MySchedulingVKR/Views/Teachers/Edit.cshtml
@model MySchedulingVKR.Models.Teacher

@{
    ViewData["Title"] = "Edit";
}
<style>
    .first {
        margin-left: 50px;
    }

    input {
        font-size: 16px;
    }
</style>

<div class="first">
    <h1>Внести изменения об информации преподавателя</h1>

    <h4>Преподаватель</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Login" class="control-label">Логин</label>
                    <input asp-for="Login" class="form-control" />
                    <span asp-validation-for="Login" class="text-danger"></span><br />
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label">Пароль</label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span><br />
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Имя</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span><br />
                </div>
                <div class="form-group">
                    <label asp-for="Surname" class="control-label">Фамилия</label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span><br />
                </div>
                <div class="form-group">
                    <label asp-for="SubjectId" class="control-label">Предмет</label>
                    <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectName"></select>
                    <span asp-validation-for="SubjectId" class="text-danger"></span>

                    <input type="hidden" asp-for="OrganizationId"/>
                </div>
                <div class="form-group">
                    <br /><input type="submit" value="Сохранить" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MySchedulingVKR/Views/Teachers/Menu.cshtml
@model MySchedulingVKR.ViewModels.TeacherViewLesson

@{
    ViewData["Title"] = "Menu";
}

<style>
    h1 {
        margin-top: 50px;
        font-size: 32px;
        text-align: center;
    }

    h4 {
        font-size: 26px;
    }

    a {
        color: #77804f;
        text-decoration: none;
    }

    .centered-content {
        max-width: 1200px;
        margin: auto;
        padding: 20px;
    }

    .info-section, .action-buttons, .schedule-list {
        margin-bottom: 20px;
    }

    .schedule-list table td a{
        float: right;
        margin-left: 10px;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
    }

        .table th, .table td {
            padding: 12px 15px;
            text-align: left;
            border: 1px solid #ddd;
            text-align: center;
        }

        .table tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table th {
            background-color: #77804f;
            color: white;
            border: none;
        }

</style>

<h1>Меню преподавателя</h1>

<div class="centered-content">
    <div class="info-section">
        <h4>Информация о преподавателе</h4>

        <dl class="row">
            <dt class="col-sm-2">
                Логин
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Teacher.Login)
            </dd>
            <dt class="col-sm-2">
                Пароль
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Teacher.Password)
            </dd>
            <dt class="col-sm-2">
                Имя
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Teacher.Name)
            </dd>
            <dt class="col-sm-2">
                Фамилия
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Teacher.Surname)
            </dd>
            <dt class="col-sm-2">
                Организация
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Teacher.Organization.Name)
            </dd>
            <dt class="col-sm-2">
                Предмет
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Teacher.Subject.Name)
            </dd>
        </dl>
        <a asp-action="EditTeacher" asp-route-id="@Model.Teacher.Id">Редактировать информацию</a>

    </div>

    <div class="action-buttons">
        <a asp-action="ScheduleTeachers" asp-route-id="@Model.Teacher.Id">Расписание занятий</a>
    </div>

    <div class="schedule-list">
        <h4>График планируемых занятий</h4>
        <p><a asp-area="" asp-controller="Lessons" asp-action="Create" asp-route-id="">Добавить новое занятие</a></p>
        <table class="table">
            <tr>
                <th>Дата</th>
                <th>День недели</th>
                <th>Время</th>
                <th></th>
            </tr>
            @foreach (var item in Model.Lessons)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DayOfTheWeek)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Time)
                    </td>
                    <td>
                        <a asp-area="" asp-controller="Lessons" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        <a asp-area="" asp-controller="Lessons" asp-action="Details" asp-route-id="@item.Id">Details  |</a>
                        <a asp-area="" asp-controller="Lessons" asp-action="Edit" asp-route-id="@item.Id">Edit  |</a>
                    </td>
                </tr>
            }
        </table>
    </div>

</div>