MySchedulingVKR/Models/Organization.cs
using System;
using System.Collections.Generic;

namespace MySchedulingVKR.Models;

public partial class Organization
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Login { get; set; } = null!;

    public string Password { get; set; } = null!;

    public string Specialization {  get; set; } = null!;

    public virtual ICollection<Teacher> Teachers { get; set; } = new List<Teacher>();

    public virtual ICollection<OrganizationSubject> OrganizationSubjects { get; set; } = new List<OrganizationSubject>();

}

MySchedulingVKR/Models/ScheduleTeacher.cs
using System;
using System.Collections.Generic;

namespace MySchedulingVKR.Models;

public partial class ScheduleTeacher
{
    public int ScheduleId { get; set; }

    public int TeacherId { get; set; }

    public virtual Schedule? Schedule { get; set; } = null!;

    public virtual Teacher? Teacher { get; set; } = null!;
}

MySchedulingVKR/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulingVKR;
using MySchedulingVKR.Models;
using MySchedulingVKR.ViewModels;

namespace MySchedulingVKR.Controllers
{
    public class OrganizationsController : Controller
    {
        private readonly DbSchedulingContext _context;

        public OrganizationsController(DbSchedulingContext context)
        {
            _context = context;
        }

        //Регистрация организации
        // GET: Organizations/Registration
        public IActionResult Registration()
        {
            return View();
        }
        // POST: Organizations/Registration
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Registration([Bind("Id,Name,Login,Password, Specialization")] Organization organization)
        {
            var existingOrganization = await _context.Organizations.FirstOrDefaultAsync(o => o.Login == organization.Login);

            if (existingOrganization != null)
            {
                ModelState.AddModelError("Login", "Логин уже используется.");
                return View(organization);
            }
            else if (ModelState.IsValid)
            {
                _context.Add(organization);
                await _context.SaveChangesAsync();
                return RedirectToAction("Menu", "Organizations", new { id = organization.Id });
            }

            return View(organization);
        }
        
        //Авторизация организации
        // GET: Organizations/Authorization
        public IActionResult Authorization()
        {
            return View();
        }
        // POST: Organizations/Authorization
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Authorization([Bind("Login,Password")] Organization organization)
        {

            var user = await _context.Organizations.FirstOrDefaultAsync(o => o.Login == organization.Login && o.Password == organization.Password);

            // Проверка введенных данных пользователя
            if (user != null)
            {
                return RedirectToAction("Menu", "Organizations", new { id = user.Id });
            }
            else
            {
                ViewBag.ErrorMessage = "Неверный логин или пароль";
                return View(user);
            }
        }

        //Меню организации
        // GET: Organizations/Menu/5
        [HttpGet]
        public async Task<IActionResult> Menu(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viewModel = new OrganizationViewSubjectAndTeacher();
            viewModel.Organizations = await _context.Organizations
                .Include(o => o.OrganizationSubjects)
                    .ThenInclude(s => s.Subject)
                .Include(o => o.Teachers)
                    .ThenInclude(t =>  t.Subject)
                .AsNoTracking()
                .ToListAsync();

            if (id != null)
            {
                ViewData["Id"] = id;

                TempData["OrganizationId"] = id;

                Organization organization = viewModel.Organizations.Where(
                    o => o.Id == id).Single();

                viewModel.Organization = organization;

                viewModel.Subjects = organization.OrganizationSubjects.Select(s => s.Subject);

                viewModel.Teachers = organization.Teachers;
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ScheduleTeachers(int? id)
        {

            if(id == null)
            {
                return NotFound();
            }

            var schedule = await _context.Organizations
                  .Include(o => o.Teachers)
                      .ThenInclude(t => t.ScheduleTeachers)
                      .ThenInclude(s => s.Schedule)
                      .ThenInclude(s => s.Lesson)
                   .FirstOrDefaultAsync(o => o.Id == id);

            return View(schedule);
        }

        //Редактирование
        // GET: Organizations/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organizations.FindAsync(id);
            if (organization == null)
            {
                return NotFound();
            }
            return View(organization);
        }
        // POST: Organizations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Login,Password, Specialization")] Organization organization)
        {
            if (id != organization.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(organization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganizationExists(organization.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Menu", "Organizations", new { id = organization.Id });
            }
            return View(organization);
        }

        //Удаление
        // GET: Organizations/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organizations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }
        // POST: Organizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var organization = await _context.Organizations.FindAsync(id);
            if (organization != null)
            {
                _context.Organizations.Remove(organization);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Home", "Index");
        }

        private bool OrganizationExists(int id)
        {
            return _context.Organizations.Any(e => e.Id == id);
        }
    }
}

MySchedulingVKR/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MySchedulingVKR;
using MySchedulingVKR.Models;

namespace MySchedulingVKR.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly DbSchedulingContext _context;

        public SubjectsController(DbSchedulingContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Subjects.ToListAsync());
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Subjects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Subject subject)
        {
            int organId = Convert.ToInt32(TempData["OrganizationId"]);
            OrganizationSubject organizationSubject = new OrganizationSubject();

            if (ModelState.IsValid)
            {
                var existingSubject = await _context.Subjects.FirstOrDefaultAsync(o => o.Name == subject.Name);
                
                if (existingSubject != null)
                {
                    organizationSubject.SubjectId = existingSubject.Id;
                    organizationSubject.OrganizationId = organId;
                    _context.OrganizationSubjects.Add(organizationSubject);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Menu", "Organizations", new { id = organId });
                }
                else
                {
                    _context.Subjects.Add(subject);
                    await _context.SaveChangesAsync();

                    organizationSubject.SubjectId = subject.Id;
                    organizationSubject.OrganizationId = organId;
                    _context.OrganizationSubjects.Add(organizationSubject);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Menu", "Organizations", new { id = organId });
                }
            }

            return View(subject);
        }

        // GET: Subjects/Edit/5        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.FindAsync(id);

            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                int organizationId = Convert.ToInt32(TempData["OrganizationId"]);
                return RedirectToAction("Menu", "Organizations", new { id =  organizationId});
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _context.Subjects.FindAsync(id);
            if (subject != null)
            {
                _context.Subjects.Remove(subject);
            }

            await _context.SaveChangesAsync();
            int organizationId = Convert.ToInt32(TempData["OrganizationId"]);
            return RedirectToAction("Menu", "Organizations", new { id = organizationId });
        }

        private bool SubjectExists(int id)
        {
            return _context.Subjects.Any(e => e.Id == id);
        }
    }
}

MySchedulingVKR/Views/Organizations/Authorization.cshtml
@model MySchedulingVKR.Models.Organization
@{
    ViewData["Title"] = "Authorization";
}

<style>
    h2 {
        margin-top: 50px;
        font-size: 32px;
        color: #122400;
        text-align: center;
        padding-bottom: 50px;
    }

    form {
        text-align: center;
        width: 300px;
        margin: 0 auto;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }

    label {
        display: block;
        margin-top: 20px;
    }

    input[type="text"], input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    input[type="checkbox"] {
        margin-top: 25px;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        margin-top: 20px;
        background-color: #77804f;
        color: white;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        button:hover {
            background-color: #0056b3;
        }

    p {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

        a:hover {
            text-decoration: underline;
        }
</style>

<h2>Авторизация организации дополнительного образования</h2>

<form asp-action="Authorization" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <p class="text-danger">@ViewBag.ErrorMessage</p>

    <label for="login">Логин:</label>
    <input asp-for="Login" type="text" id="login" name="login" required><br>

    <label for="password">Пароль:</label>
    <input asp-for="Password" type="password" id="password" name="password" required><br>

    <button type="submit">Войти</button>
</form>

MySchedulingVKR/Views/Organizations/Delete.cshtml
@model MySchedulingVKR.Models.Organization

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление аккаунта</h1>

<h3>Вы дйствительно хотите удалить аккаунт?</h3>
<div>
    <h4>Организация</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Название
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Логин
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Login)
        </dd>
        <dt class = "col-sm-2">
            Пароль
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
    </form>
</div>

MySchedulingVKR/Views/Organizations/Edit.cshtml
@model MySchedulingVKR.Models.Organization

@{
    ViewData["Title"] = "Edit";
}
<style>
    .first {
        margin-left: 50px;
    }

    input {
        font-size: 16px;
    }
</style>

<div class="first">
    <h1>Внесите изменения об информации организации</h1>

    <h4>Организация дополнительного образования</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Название организации</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span><br>
                </div>
                <div class="form-group">
                    <label asp-for="Login" class="control-label">Логин</label>
                    <input asp-for="Login" class="form-control" />
                    <span asp-validation-for="Login" class="text-danger"></span><br>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label">Пароль</label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span><br />
                </div>
                <div>
                    <label asp-for="Specialization" class="control-label">Специализация:</label>
                    <input asp-for="Specialization" class="form-control" />
                    <span asp-validation-for="Specialization" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <br /><input type="submit" value="Сохранить" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MySchedulingVKR/Views/Organizations/Menu.cshtml
@model MySchedulingVKR.ViewModels.OrganizationViewSubjectAndTeacher


@{
    ViewData["Title"] = "Menu";
}

<style>
    h1 {
        margin-top: 50px;
        font-size: 32px;
        text-align: center;
    }

    h4 {
        font-size: 26px;
    }

    a {
        color: #77804f;
        text-decoration: none;
    }

    .subject-list table td a, .teacher-list table td a {
        float: right; 
        margin-left: 10px; 
    }

    .centered-content {
        max-width: 1200px; 
        margin: auto; 
        padding: 20px; 
    }

    .info-section, .action-buttons, .subject-list, .teacher-list {
        margin-bottom: 20px; 
    }

    .table {
        width: 100%; 
        border-collapse: collapse; 
    }

        .table th, .table td {
            padding: 12px 15px; 
            text-align: left; 
            border: 1px solid #ddd;
            text-align: center;
        }

        .table tr:nth-child(even) {
            background-color: #f2f2f2; 
        }

        .table th {
            background-color: #77804f; 
            color: white; 
            border: none;           
        }
</style>

<h1>Меню организации</h1>

<div class="centered-content">
   
    <div class="info-section">
        <h4>Информация</h4>
        <dl class="row">
            <dt class="col-sm-2">
                Название
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Organization.Name)
            </dd>
            <dt class="col-sm-2">
                Логин
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Organization.Login)
            </dd>
            <dt class="col-sm-2">
                Специализация
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Organization.Specialization)
            </dd>
        </dl>
        <a asp-action="Edit" asp-route-id="@Model.Organization.Id">Редактировать информацию</a>
        <a asp-action="Delete" asp-route-id="@Model.Organization.Id">Удалить организацию</a>
    </div>

    <div class="action-buttons">
        <a asp-action="ScheduleTeachers" asp-route-id="@Model.Organization.Id">Расписание занятий</a>
    </div>

    <div class="subject-list">
        <h4>Список предметов</h4>
        <p><a asp-area="" asp-controller="Subjects" asp-action="Create">Добавить новый предмет</a></p>
        <table class="table">
            <tr>
                <th>Название</th>
                <th></th>
            </tr>
            @foreach (var item in Model.Subjects)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a asp-area="" asp-controller="Subjects" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        <a asp-area="" asp-controller="Subjects" asp-action="Details" asp-route-id="@item.Id">Details  |</a>
                        <a asp-area="" asp-controller="Subjects" asp-action="Edit" asp-route-id="@item.Id">Edit  |</a>
                    </td>
                </tr>
            }
        </table>
    </div>
   
    <div class="teacher-list">
        <h4>Список преподавателей</h4>
        <p><a asp-area="" asp-controller="Teachers" asp-action="Create">Добавить нового преподавателя</a></p>
        <table class="table">
            <tr>
                <th>Логин</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Предмет</th>
                <th></th>
            </tr>
            @foreach (var item in Model.Teachers)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Login)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Subject.Name)
                    </td>
                    <td>
                        <a asp-area="" asp-controller="Teachers" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        <a asp-area="" asp-controller="Teachers" asp-action="Details" asp-route-id="@item.Id">Details  |</a>
                        <a asp-area="" asp-controller="Teachers" asp-action="Edit" asp-route-id="@item.Id">Edit  |</a>
                    </td>
                </tr>
            }
        </table>
    </div>
    
</div>
   

MySchedulingVKR/Views/Organizations/Registration.cshtml
    @model MySchedulingVKR.Models.Organization
@{
    ViewData["Title"] = "Registration";
}

<style>
    h2 {
        margin-top: 50px;
        font-size: 32px;
        color: #122400;
        text-align: center; 
        padding-bottom: 50px;
    }

    form {
        text-align: center;
        width: 300px;
        margin: 0 auto;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }

    label {
        display: block;
        margin-top: 20px;
    }

    input[type="text"], input[type="password"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
        margin-bottom: 20px;
    }

    input[type="checkbox"] {
        margin-top: 25px;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        margin-top: 20px;
        background-color: #77804f;
        color: white;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        button:hover {
            background-color: #0056b3;
        }

    p {
        text-align: center;
        margin-top: 20px;
    }

    a {
        color: #007bff;
        text-decoration: none;
    }

        a:hover {
            text-decoration: underline;
        }
</style>

<h2>Регистрация организации дополнительного образования</h2>

<form asp-action="Registration">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <label for="name">Название организации:</label>
    <input asp-for="Name" type="text" id="name" name="name" required>
    <span asp-validation-for="Name" class="text-danger"></span><br />

    <label for="login">Логин:</label>
    <input asp-for="Login" type="text" id="login" name="login" required>
    <span asp-validation-for="Login" class="text-danger" data-valmsg-for="Login"></span><br />

    <label for="password">Пароль:</label>
    <input asp-for="Password" type="password" id="password" name="password" required>
    <span asp-validation-for="Password" class="text-danger"></span><br />

    <label for="specialization">Специализация:</label>
    <input asp-for="Specialization" type="text" id="specialization" name="specialization" required>
    <span asp-validation-for="Specialization" class="text-danger"></span><br />

    <input type="checkbox" id="terms" name="terms" required>
    <label for="terms">Я согласен с условиями использования</label><br>

    <button type="submit"<a asp-area="" asp-controller="Organizations" asp-action="Registation">Зарегистрироваться</a></button>
</form>

<p>Уже есть аккаунт? <a asp-area="" asp-controller="Organizations" asp-action="Authorization">Войти</a></p>

MySchedulingVKR/Views/Organizations/ScheduleTeachers.cshtml
@model MySchedulingVKR.Models.Organization
@{
    ViewData["Title"] = "ScheduleTeachers";
}

<style>
    h1 {
        margin-top: 50px;
        text-align: center;
    }

    a {
        color: #77804f;
        text-decoration: none;
    }

    .centered-content {
        max-width: 1200px;
        margin: auto;
        padding: 20px;
    }

    .info-section, .action-buttons, .schedule-list {
        margin-bottom: 20px;
    }

        .schedule-list table td a {
            float: right;
            margin-left: 10px;
        }

    .table {
        width: 100%;
        border-collapse: collapse;
    }

        .table th, .table td {
            padding: 12px 15px;
            border: 1px solid #ddd;
            text-align: center;
        }

        .table th {
            background-color: #77804f;
            color: white;
        }

    tr:nth-child(even) {
        background-color: #f2f2f2; /* Цвет фона для четных строк */
    }

    .inner-table {
        width: 100%;
        border-collapse: collapse;
    }

        .inner-table th, .inner-table td {
            padding: 8px;
            text-align: center; /* Центрирование текста */
            border-bottom: 1px solid #ddd;
        }

        .inner-table th {
            background-color: #77804f;
        }

    .full-width-button {
        width: 100%; /* Кнопка занимает всю ширину строки */
        display: block; /* Кнопка ведет себя как блочный элемент */
        background-color: #77804f;
    }

    .teacher-name-cell {
        justify-content: center; /* Центрирование по горизонтали */
        align-items: center; /* Центрирование по вертикали */
        height: 100%; /* Высота ячейки */
    }
</style>

<h1>Расписание занятий преподавателей</h1>

<div class="centered-content">
    <div class="info-section">
        <h4>Информация о организации</h4>
        <dl class="row">
            <dt class="col-sm-2">
                Организация
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
    </div>

    <div class="action-buttons">
        <a asp-action="Menu" asp-route-id="@Model.Id">Вернуться в меню</a>
    </div>

    <div class="schedule-list">
        <h4>Расписание преподавателей</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>Преподаватель</th>
                    <th>Занятие</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Teachers)
                {
                    <tr>
                        <td>@item.Name @item.Surname</td>
                        <td>
                            <table class="inner-table">
                                <thead>
                                    <tr>
                                        <th>День недели</th>
                                        <th>Дата</th>
                                        <th>Время</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var schedule in item.ScheduleTeachers.Select(s => s.Schedule))
                                    {
                                        <tr>
                                            <td>@schedule.Lesson.DayOfTheWeek</td>
                                            <td>@schedule.Lesson.Date</td>
                                            <td>@schedule.Lesson.Time</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>